{
  "hash": "7cc47d139f9a815a91bd9e7377063238c69a0423",
  "hash_short": "7cc47d13",
  "subject": "cxgb3: Missing rtnl lock in error recovery",
  "body": "When exercising error injection on IBM pseries machine, I hit the\nfollowing warning:\n\n[  251.450043] RTAS: event: 89, Type: Platform Error, Severity: 2\n[  253.549822] cxgb3 0006:01:00.0: enabling device (0140 -> 0142)\n[  253.713560] cxgb3 0006:01:00.0: adapter recovering, PEX ERR 0x100\n[  254.895437] RTNL: assertion failed at net/core/dev.c (2031)\n[  254.895467] CPU: 6 PID: 5449 Comm: eehd Tainted: G        W    3.10.0-rc7-00157-gea461ab #19\n[  254.895474] Call Trace:\n[  254.895483] [c000000fac56f7d0] [c000000000014dcc] .show_stack+0x7c/0x1f0 (unreliable)\n[  254.895493] [c000000fac56f8a0] [c0000000007ba318] .dump_stack+0x28/0x3c\n[  254.895500] [c000000fac56f910] [c0000000006c0384] .netif_set_real_num_tx_queues+0x224/0x230\n[  254.895515] [c000000fac56f9b0] [d00000000ef35510] .cxgb_open+0x80/0x3f0 [cxgb3]\n[  254.895525] [c000000fac56fa50] [d00000000ef35914] .t3_resume_ports+0x94/0x100 [cxgb3]\n[  254.895533] [c000000fac56fae0] [c00000000005fc8c] .eeh_report_resume+0x8c/0xd0\n[  254.895539] [c000000fac56fb60] [c00000000005e9fc] .eeh_pe_dev_traverse+0x9c/0x190\n[  254.895545] [c000000fac56fc10] [c000000000060000] .eeh_handle_event+0x110/0x330\n[  254.895551] [c000000fac56fca0] [c000000000060350] .eeh_event_handler+0x130/0x1a0\n[  254.895558] [c000000fac56fd30] [c0000000000ad758] .kthread+0xe8/0xf0\n[  254.895566] [c000000fac56fe30] [c00000000000a05c] .ret_from_kernel_thread+0x5c/0x80\n\nIt appears that t3_resume_ports() is called with the rtnl_lock held from\nthe fatal error task but not from the PCI error callbacks. This fixes it.\n\nSigned-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>\nSigned-off-by: David S. Miller <davem@davemloft.net>",
  "full_message": "cxgb3: Missing rtnl lock in error recovery\n\nWhen exercising error injection on IBM pseries machine, I hit the\nfollowing warning:\n\n[  251.450043] RTAS: event: 89, Type: Platform Error, Severity: 2\n[  253.549822] cxgb3 0006:01:00.0: enabling device (0140 -> 0142)\n[  253.713560] cxgb3 0006:01:00.0: adapter recovering, PEX ERR 0x100\n[  254.895437] RTNL: assertion failed at net/core/dev.c (2031)\n[  254.895467] CPU: 6 PID: 5449 Comm: eehd Tainted: G        W    3.10.0-rc7-00157-gea461ab #19\n[  254.895474] Call Trace:\n[  254.895483] [c000000fac56f7d0] [c000000000014dcc] .show_stack+0x7c/0x1f0 (unreliable)\n[  254.895493] [c000000fac56f8a0] [c0000000007ba318] .dump_stack+0x28/0x3c\n[  254.895500] [c000000fac56f910] [c0000000006c0384] .netif_set_real_num_tx_queues+0x224/0x230\n[  254.895515] [c000000fac56f9b0] [d00000000ef35510] .cxgb_open+0x80/0x3f0 [cxgb3]\n[  254.895525] [c000000fac56fa50] [d00000000ef35914] .t3_resume_ports+0x94/0x100 [cxgb3]\n[  254.895533] [c000000fac56fae0] [c00000000005fc8c] .eeh_report_resume+0x8c/0xd0\n[  254.895539] [c000000fac56fb60] [c00000000005e9fc] .eeh_pe_dev_traverse+0x9c/0x190\n[  254.895545] [c000000fac56fc10] [c000000000060000] .eeh_handle_event+0x110/0x330\n[  254.895551] [c000000fac56fca0] [c000000000060350] .eeh_event_handler+0x130/0x1a0\n[  254.895558] [c000000fac56fd30] [c0000000000ad758] .kthread+0xe8/0xf0\n[  254.895566] [c000000fac56fe30] [c00000000000a05c] .ret_from_kernel_thread+0x5c/0x80\n\nIt appears that t3_resume_ports() is called with the rtnl_lock held from\nthe fatal error task but not from the PCI error callbacks. This fixes it.\n\nSigned-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>\nSigned-off-by: David S. Miller <davem@davemloft.net>",
  "author_name": "Benjamin Herrenschmidt",
  "author_email": "benh@kernel.crashing.org",
  "author_date": "Sun Jun 30 14:37:11 2013 +1000",
  "author_date_iso": "2013-06-30T14:37:11+10:00",
  "committer_name": "David S. Miller",
  "committer_email": "davem@davemloft.net",
  "committer_date": "Tue Jul 2 12:37:48 2013 -0700",
  "committer_date_iso": "2013-07-02T12:37:48-07:00",
  "files_changed": [
    "drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c"
  ],
  "files_changed_count": 1,
  "stats": [
    {
      "file": "drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c",
      "insertions": 2,
      "deletions": 0
    }
  ],
  "total_insertions": 2,
  "total_deletions": 0,
  "total_changes": 2,
  "parents": [
    "1fc4c84d49558ceca04761abd3f7eb5224af75b2"
  ],
  "branches": [
    "* development",
    "master",
    "remotes/origin/HEAD -> origin/master",
    "remotes/origin/master"
  ],
  "tags": [
    "v3.11",
    "v3.11-rc1",
    "v3.11-rc2",
    "v3.11-rc3",
    "v3.11-rc4",
    "v3.11-rc5",
    "v3.11-rc6",
    "v3.11-rc7",
    "v3.12",
    "v3.12-rc1"
  ],
  "is_merge": false,
  "security_info": {
    "cve_ids": [],
    "security_keywords": [
      "injection"
    ]
  },
  "fix_type": "security",
  "file_results": [
    {
      "file": "drivers/net/ethernet/chelsio/cxgb3/cxgb3_main.c",
      "pre_version": false,
      "post_version": true,
      "patch": true
    }
  ]
}